### ISSUE TITLE
output file

### ISSUE THREAD

**Issue by TheodoreZhao** [mp2893/med2vec#7]
Hi Edward,
I have run your code on my dataset and got the .npz files. I find it contains 6 numpy.array variables W_emb b_output b_hidden b_emb W_output W_hidden. But on the GitHub Repo I can’t find further description about these output variables. Can you give some detailed instruction about the output? How can I get the code and visit representation?

**Comment by mp2893** [comment]
Hi Theodore,

First of all, let me explain how to obtain vector representations for each code.
If you look at Fig.2 of the paper, ReLU(W_emb x_t + b_emb) is the representation of multiple codes (since x_t will have multiple 1s). If you make x_t such that it has only a single 1, then ReLU(W_emb x_t + b_emb) will be a representation of a single code. For example, if the coordinate 0 represents "Lung cancer" and you make x_t such that <1,0,0,0,0,....,0,0>, then ReLU(W_emb x_t + b_emb) will be the vector representation of "Lung cancer"

For visit representation, you can derive the code-level representation using u_t = ReLU(W_hidden x_t + b_hidden), possibly with a multi-hot vector, then use v_t = ReLU(W_hidden u_t + b_hidden) to derive the visit representation.

You can also read section 3.1 of my [paper](http://www.kdd.org/kdd2016/papers/files/rpp0303-choiA.pdf). Figure 2 will also help you.

Thanks,
Ed

**Comment by TheodoreZhao** [comment]
Thanks a lot! It is very clear with your explanation. About your mentioned above,

> For visit representation, you can derive the code-level representation using u_t = ReLU(W_hidden x_t + b_hidden)
 I think the code-level representation should be 
u_t = ReLU(W_emb x_t + b_emb
?

**Comment by mp2893** [comment]
Yeah that's correct. My mistake.
